# Generated by Django 5.0.2 on 2024-02-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditapp', '0002_customer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_debt',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
