# Generated by Django 5.0.2 on 2024-02-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditapp', '0004_alter_loan_end_date_alter_loan_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='approved_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
