# Generated by Django 5.0.2 on 2024-02-16 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditapp', '0005_alter_customer_approved_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='monthly_salary',
            new_name='monthly_income',
        ),
    ]
