# Generated by Django 5.0.2 on 2024-02-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditapp', '0006_rename_monthly_salary_customer_monthly_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(max_length=10000, null=True),
        ),
    ]
