# Generated by Django 5.0.2 on 2024-02-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditapp', '0007_customer_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='monthly_repayment',
            new_name='monthly_installment',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
    ]
