version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: skillysdb
      POSTGRES_USER: skillyboy
      POSTGRES_PASSWORD: skilly1234
    ports:
      - "8000:8000"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/creditapp:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

